#!/bin/sh
./graphplot_t_min_tx.py
./graphplot_e_min_cpu.py
./graphplot_e_max_cpu.py
./graphplot_u_min_cpu.py
./graphplot_u_min_tx.py
./graphplot_e_max_tx.py
./graphplot_u_max_tx.py
./graphplot_t_max_tx.py
./graphplot_e_min_tx.py
./graphplot_t_max_cpu.py
./graphplot_u_max_cpu.py
./graphplot_t_min_cpu.py
